version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    # command: /opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic logstash_logs
    container_name: kafka
  logstash:
    image: halosan/logstash:5.5
    ports:
      - "10000:10000"
    links:
      - kafka
    # volumes:
    #   - ./logstash_settings/:/usr/share/logstash/config/
    #   - ./logstash_pipeline/:/usr/share/logstash/pipeline/
    container_name: logstash
